BOOKS = [
    {
        "id": 1,
        "title": "Dune",
        "author": "Frank Herbert",
        "genres": ["science fiction", "adventure", "politics"],
        "keywords": ["desert", "empire", "strategy", "ecology"],
        "rating": 4.8,
        "year": 1965,
    },
    {
        "id": 2,
        "title": "Foundation",
        "author": "Isaac Asimov",
        "genres": ["science fiction", "history", "strategy"],
        "keywords": ["empire", "prediction", "civilization", "science"],
        "rating": 4.6,
        "year": 1951,
    },
    {
        "id": 3,
        "title": "1984",
        "author": "George Orwell",
        "genres": ["dystopia", "politics", "classic"],
        "keywords": ["surveillance", "state", "freedom", "propaganda"],
        "rating": 4.7,
        "year": 1949,
    },
    {
        "id": 4,
        "title": "Animal Farm",
        "author": "George Orwell",
        "genres": ["classic", "politics", "satire"],
        "keywords": ["power", "revolution", "society", "allegory"],
        "rating": 4.4,
        "year": 1945,
    },
    {
        "id": 5,
        "title": "The Hobbit",
        "author": "J. R. R. Tolkien",
        "genres": ["fantasy", "adventure", "classic"],
        "keywords": ["journey", "dragon", "friendship", "quest"],
        "rating": 4.8,
        "year": 1937,
    },
    {
        "id": 6,
        "title": "The Fellowship of the Ring",
        "author": "J. R. R. Tolkien",
        "genres": ["fantasy", "adventure", "classic"],
        "keywords": ["quest", "friendship", "ring", "war"],
        "rating": 4.9,
        "year": 1954,
    },
    {
        "id": 7,
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J. K. Rowling",
        "genres": ["fantasy", "young adult", "adventure"],
        "keywords": ["magic", "school", "friendship", "mystery"],
        "rating": 4.7,
        "year": 1997,
    },
    {
        "id": 8,
        "title": "The Name of the Wind",
        "author": "Patrick Rothfuss",
        "genres": ["fantasy", "adventure", "drama"],
        "keywords": ["magic", "music", "school", "legend"],
        "rating": 4.6,
        "year": 2007,
    },
    {
        "id": 9,
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "genres": ["romance", "classic", "drama"],
        "keywords": ["family", "society", "marriage", "wit"],
        "rating": 4.5,
        "year": 1813,
    },
    {
        "id": 10,
        "title": "Jane Eyre",
        "author": "Charlotte Bronte",
        "genres": ["romance", "classic", "drama"],
        "keywords": ["independence", "mystery", "identity", "love"],
        "rating": 4.4,
        "year": 1847,
    },
    {
        "id": 11,
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "genres": ["philosophy", "adventure", "self improvement"],
        "keywords": ["dreams", "journey", "purpose", "destiny"],
        "rating": 4.2,
        "year": 1988,
    },
    {
        "id": 12,
        "title": "Atomic Habits",
        "author": "James Clear",
        "genres": ["self improvement", "psychology", "productivity"],
        "keywords": ["habits", "goals", "systems", "behavior"],
        "rating": 4.8,
        "year": 2018,
    },
    {
        "id": 13,
        "title": "Deep Work",
        "author": "Cal Newport",
        "genres": ["productivity", "technology", "self improvement"],
        "keywords": ["focus", "work", "attention", "career"],
        "rating": 4.5,
        "year": 2016,
    },
    {
        "id": 14,
        "title": "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "genres": ["psychology", "science", "business"],
        "keywords": ["decision", "bias", "mind", "thinking"],
        "rating": 4.6,
        "year": 2011,
    },
    {
        "id": 15,
        "title": "The Lean Startup",
        "author": "Eric Ries",
        "genres": ["business", "technology", "entrepreneurship"],
        "keywords": ["startup", "experiment", "product", "innovation"],
        "rating": 4.3,
        "year": 2011,
    },
    {
        "id": 16,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "genres": ["technology", "programming", "software"],
        "keywords": ["code", "quality", "design", "maintenance"],
        "rating": 4.7,
        "year": 2008,
    },
    {
        "id": 17,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "genres": ["programming", "technology", "python"],
        "keywords": ["python", "advanced", "functions", "objects"],
        "rating": 4.7,
        "year": 2015,
    },
    {
        "id": 18,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "genres": ["programming", "python", "automation"],
        "keywords": ["python", "files", "scraping", "automation"],
        "rating": 4.6,
        "year": 2015,
    },
    {
        "id": 19,
        "title": "The Girl with the Dragon Tattoo",
        "author": "Stieg Larsson",
        "genres": ["mystery", "crime", "thriller"],
        "keywords": ["investigation", "crime", "journalism", "secrets"],
        "rating": 4.4,
        "year": 2005,
    },
    {
        "id": 20,
        "title": "Gone Girl",
        "author": "Gillian Flynn",
        "genres": ["thriller", "mystery", "drama"],
        "keywords": ["marriage", "media", "crime", "twist"],
        "rating": 4.1,
        "year": 2012,
    },
]
